Controllers/Landing4Controller.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using PamaWeb.Models;

namespace PamaWeb.Controllers
{
    public class Landing4Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        private string _currentLanguage;
        private string CurrentLanguage
        {
            get
            {
                if (!string.IsNullOrEmpty(_currentLanguage))
                    return _currentLanguage;

                if (string.IsNullOrEmpty(_currentLanguage))
                {
                    var feature = HttpContext.Features.Get<IRequestCultureFeature>();
                    _currentLanguage = feature.RequestCulture.Culture.TwoLetterISOLanguageName.ToLower();
                }

                return _currentLanguage;
            }
        }

        public ActionResult RedirectToDefaultLanguageLanding()
        {
            var culture = CurrentLanguage;
            if (culture != "en")
                culture = "en";
            return RedirectToAction("Index", new { culture });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Landing4/Index.cshtml
@{
    Layout = "";
}
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PT PAMAPERSADA NUSANTARA</title>
    <link href="~/faviconpama.ico" rel="shortcut icon" type="image/x-icon" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <!-- Custom Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/normalize.css" />
    <link rel="stylesheet" href="~/css/landing4.css" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="~/js/clarity.js" type="text/javascript"></script>
    <!-- </head> -->
</head>
<body>
    <audio loop id="player">
        <source src="~/music/Sailing_boat.mp3">
    </audio>
    <audio loop id="talking">
        <source src="~/music/radio_communication.mp3">
    </audio>
    <div class="outer-wrapper">
        <div class="wrapper">
            <div class="slide one" id="s1">
                <div class="img-latar">
                    <img src="~/images/png hobo lobo/png segment 5/10. background.png" alt="" style="position:relative; width: 3250px;" />
                </div>
                <div class="img-penampungan">
                    <img src="~/images/png hobo lobo/png segment 5/4. penampungan.png" alt="" style="position:absolute; width: 1050px; top: 0px; left: 0px;" />
                </div>
                <div class="img-2pekerja">
                    <img src="~/images/png hobo lobo/gif hobo segment 5/3.2 pekerja.gif" alt="" style="position:absolute; width: 560px; top: 11px; left: -60px;" />
                </div>
                <div class="img-trukgandeng">
                    <img src="~/images/png hobo lobo/png segment 5/6. truk gandeng 3.png" alt="" style="position:absolute; width: 1200px; top: 8px; left: 1330px;" />
                </div>
                <div class="img-trukpengisian">
                    <img src="~/images/png hobo lobo/png segment 5/2. truk pengisian.png" alt="" style="position:absolute; width: 958px; top: 0px; left: 953px;" />
                </div>
                <div class="img-operatorht">
                    <img src="~/images/png hobo lobo/png segment 5/1. bapak megang ht.png" alt="" style="position:absolute; width: 358px; top: 0px; left: 870px;" />
                </div>
                <div class="img-pengisiantongkang">
                    <img src="~/images/png hobo lobo/gif hobo segment 5/7. pengisisan tongkang.gif" alt="" style="position:absolute; width: 658px; top: 0px; left: 2053px;" />
                </div>
                <div class="img-kapaltongkang">
                    <img src="~/images/png hobo lobo/gif hobo segment 5/5. kapal tongkang.gif" alt="" style="position:absolute; width: 950px; top: 120px; left: 2200px;" />
                </div>
                <div class="img-gold">
                    <img src="~/images/png hobo lobo/gif hobo segment 5/8. gold.gif" alt="" style="position:absolute; width: 390px; top: 40px; left: 2650px;" />
                </div>
                <div class="img-pltu">
                    <img src="~/images/png hobo lobo/gif hobo segment 5/9.pltu.gif" alt="" style="position:absolute; width: 400px; top: 45px; left: 2845px;" />
                </div>
                <div class="container-fluid" style="position: fixed;">
                    <div class="row">
                        <div id="panelControl" class="col-sm-5 pt-3 pb-1">
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Landing" asp-action="Index">Story 1</a>
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Landing2" asp-action="Index">Story 2</a>
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Landing3" asp-action="Index">Story 3</a>
                            <a class="btn btn-sm btn-outline-warning active" asp-area="" asp-controller="Landing4" asp-action="Index">Story 4</a>
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Landing5" asp-action="Index">Story 5</a>
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Home" asp-action="Index" role="button" aria-disabled="true"><i class="fa fa-home"></i></a>
                            <div class="button-language mt-1">
                                <a class="btn btn-sm btn-outline-warning" href="/id">Indonesia</a>
                                <a class="btn btn-sm btn-outline-warning" href="/en">English</a>
                            </div>
                            <div class="mt-md-2">
                                <p class="glow">Please, Scroll to the Right</p>
                            </div>
                        </div>
                        <div class="col-sm-6 pt-3 narrative">
                            <p class="mb-0">
                                @Localizer["landing_body"]
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/js/landing4.js"></script>
    <!-- </body></html> -->
</body>
</html>