Controllers/LandingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using PamaWeb.Models;

namespace PamaWeb.Controllers
{
    public class LandingController : Controller
    {
        private readonly dbpamaContext _context;
        public LandingController(dbpamaContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {

            return View();
        }


        private string _currentLanguage;
        private string CurrentLanguage
        {
            get
            {
                if (!string.IsNullOrEmpty(_currentLanguage))
                    return _currentLanguage;

                if (string.IsNullOrEmpty(_currentLanguage))
                {
                    var feature = HttpContext.Features.Get<IRequestCultureFeature>();
                    _currentLanguage = feature.RequestCulture.Culture.TwoLetterISOLanguageName.ToLower();
                }

                return _currentLanguage;
            }
        }

        public ActionResult RedirectToDefaultLanguageLanding()
        {
            var culture = CurrentLanguage;
            if (culture != "en")
                culture = "en";
            return RedirectToAction("Index", new { culture });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Landing/Index.cshtml
@{
    Layout = "";
}
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PT PAMAPERSADA NUSANTARA</title>
    <link href="~/faviconpama.ico" rel="shortcut icon" type="image/x-icon" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <!-- Custom Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/normalize.css" />
    <link rel="stylesheet" href="~/css/landing.css" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="~/js/clarity.js" type="text/javascript"></script>
    <!-- </head> -->
</head>
<body>
    <audio loop id="player">
        <source src="~/music/Freesound - -Footsteps, Muddy, A.wav- by InspectorJ.mp3">
    </audio>
    <audio loop id="engine">
        <source src="~/music/Bulldozer-diesel.mp3">
    </audio>
    <div class="outer-wrapper">
        <div class="wrapper">
            <div class="slide one" id="s1">
                <div class="img-latar">
                    <img src="~/images/png hobo lobo/png segment 1/16.latar.png" alt="" style="position:relative; width: 2300px;" />
                </div>
                <div class="img-gunung">
                    <img src="~/images/png hobo lobo/png segment 1/15.gunung.png" alt="" style="position:fixed; width: 1900px; top: 25px; left: 60px;" />
                </div>
                <div class="img-rumah">
                    <img src="~/images/png hobo lobo/png segment 1/13.rumah.png" alt="" style="position:absolute; width: 2300px; top: 0px; left: 0;" />
                </div>
                <div class="img-logo">
                    <img src="~/images/png hobo lobo/png segment 1/1.logo.png" alt="" style="position:absolute; width: 175px; top: 20px; left: 20px;" />
                </div>
                <div class="img-truck3">
                    <img src="~/images/png hobo lobo/gif hobo segment 1/truck-3-jalan.gif" alt="" style="position:absolute; width: 2190px; top: 19px; left: 105px;" />
                </div>
                <div class="img-truckdozer4">
                    <img src="~/images/png hobo lobo/gif hobo segment 1/10. dozer 4 gerak.gif" alt="" style="position:absolute; width: 330px; top: 165px; left: 1680px;" />
                </div>
                <div class="img-truckdozer3">
                    <img src="~/images/png hobo lobo/gif hobo segment 1/12.dozer 3 gerak.gif" alt="" style="position:absolute; width: 210px; top: 160px; left: 1505px;" />
                </div>
                <div class="img-truckdozer2">
                    <img src="~/images/png hobo lobo/gif hobo segment 1/11. dozer 2 gerak.gif" alt="" style="position:absolute; width: 390px; top: 135px; left: 1260px;" />
                </div>
                <div class="img-truckdozer1">
                    <img src="~/images/png hobo lobo/gif hobo segment 1/9. dozer 1 gerak.gif" alt="" style="position:absolute; width: 360px; top: 175px; left: 1130px;" />
                </div>
                <div class="img-excavatorkiri">
                    <img src="~/images/png hobo lobo/gif hobo segment 1/PC-300.gif" alt="" style="position:absolute; width: 600px; top: -15px; left: 714px;" />
                </div>
                <div class="img-truckdepan">
                    <img src="~/images/png hobo lobo/png segment 1/4.truck depan.png" alt="" style="position:absolute; width: 550px; top: 34px; left: 482px;" />
                </div>
                <div class="img-plang">
                    <img src="~/images/png hobo lobo/gif hobo segment 1/5.plang nama gerak.gif" alt="" style="position:absolute; width: 430px; top: 35px; left: 1050px;" />
                </div>
                <div class="img-orang1">
                    <img src="~/images/png hobo lobo/gif hobo segment 1/2.orang-1.gif" alt="" style="position:absolute; width: 720px; top: 75px;  left: 320px;" />
                </div>
                <div class="img-excavatorkanan">
                    <img src="~/images/png hobo lobo/png segment 1/6.c300 kanan.png" alt="" style="position:absolute; width: 390px; top: 75px; left: 1880px;" />
                </div>
                <div class="img-orang2">
                    <img src="~/images/png hobo lobo/gif hobo segment 1/3. orang 2 gerak.gif" alt="" style="position:absolute; width: 525px; top: 125px; left: 1600px;" />
                </div>
                <div class="container-fluid" style="position: fixed;">
                    <div class="row">
                        <div id="panelControl" class="col-sm-5 pt-3 pb-1">
                            <a class="btn btn-sm btn-outline-warning active" asp-area="" asp-controller="Landing" asp-action="Index">Story 1</a>
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Landing2" asp-action="Index">Story 2</a>
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Landing3" asp-action="Index">Story 3</a>
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Landing4" asp-action="Index">Story 4</a>
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Landing5" asp-action="Index">Story 5</a>
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Home" asp-action="Index" role="button" aria-disabled="true"><i class="fa fa-home"></i></a>
                            <div class="button-language mt-1">
                                <a class="btn btn-sm btn-outline-warning" href="/id">Indonesia</a>
                                <a class="btn btn-sm btn-outline-warning" href="/en">English</a>
                            </div>
                            <div class="mt-md-2">
                                <p class="glow">Please, Scroll to the Right</p>
                            </div>
                        </div>
                        <div class="col-sm-6 pt-3 narrative">
                            <p class="mb-0">
                                @Localizer["landing_body"]
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/js/landing.js"></script>
    <!-- </body></html> -->
</body>
</html>