Controllers/Landing5Controller.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using PamaWeb.Models;

namespace PamaWeb.Controllers
{
    public class Landing5Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        private string _currentLanguage;
        private string CurrentLanguage
        {
            get
            {
                if (!string.IsNullOrEmpty(_currentLanguage))
                    return _currentLanguage;

                if (string.IsNullOrEmpty(_currentLanguage))
                {
                    var feature = HttpContext.Features.Get<IRequestCultureFeature>();
                    _currentLanguage = feature.RequestCulture.Culture.TwoLetterISOLanguageName.ToLower();
                }

                return _currentLanguage;
            }
        }

        public ActionResult RedirectToDefaultLanguageLanding()
        {
            var culture = CurrentLanguage;
            if (culture != "en")
                culture = "en";
            return RedirectToAction("Index", new { culture });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Landing5/Index.cshtml
@{
    Layout = "";
}
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PT PAMAPERSADA NUSANTARA</title>
    <link href="~/faviconpama.ico" rel="shortcut icon" type="image/x-icon" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <!-- Custom Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/normalize.css" />
    <link rel="stylesheet" href="~/css/landing5.css" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script src="~/js/clarity.js" type="text/javascript"></script>
    <!-- </head> -->
</head>
<body>
    <audio loop id="player">
        <source src="~/music/windmill_heli-cut.wav">
    </audio>
    <audio loop id="airplane">
        <source src="~/music/airplane_landing-cut.wav">
    </audio>
    <audio loop id="lovesong">
        <source src="~/music/Daniel-Padilla-I-Cant-Help-Falling-In-Love-With-You-Piano-Cover-by-GPiano.mp3">
    </audio>
    <div class="outer-wrapper">
        <div class="wrapper">
            <div class="slide" id="s1">
                <div class="img-latar">
                    <img src="~/images/png hobo lobo/png segment 6/12. latar.png" alt="" style="position:relative; width: 3250px;" />
                </div>
                <div class="img-love">
                    <img src="~/images/png hobo lobo/png segment 6/9. orang love.png" alt="" style="position:absolute; width: 625px; top: 0px; left: 2635px;" />
                </div>
                <div class="img-logo">
                    <img src="~/images/png hobo lobo/png segment 1/1.logo.png" alt="" style="position:absolute; width: 90px; top: 0px; left: 3165px;" />
                </div>
                <div class="img-lampu">
                    <img src="~/images/png hobo lobo/png segment 6/4. lampu.png" alt="" style="position:absolute; width: 2100px; top: 0; left: 770px;" />
                </div>
                <div class="img-pltu">
                    <img src="~/images/png hobo lobo/png segment 6/3. pltu.png" alt="" style="position:absolute; width: 435px; top: 135px; left: 0px;" />
                </div>
                <div class="img-pesawat">
                    <img src="~/images/png hobo lobo/gif hobo segment 6/pesawat.gif" alt="" style="position:absolute; width: 500px; top: 5px; left: 250px;" />
                </div>
                <div class="img-turbin">
                    <img src="~/images/png hobo lobo/png segment 6/11. turbin.png" alt="" style="position:absolute; width: 640px; top: 15px; left: 450px;" />
                </div>
                <div class="img-pc">
                    <img src="~/images/png hobo lobo/png segment 6/2. pc.png" alt="" style="position:absolute; width: 240px; top: 15px; left: 980px;" />
                </div>
                <div class="img-awan">
                    <img src="~/images/png hobo lobo/gif hobo segment 6/awan.gif" alt="" style="position:absolute; width: 1800px; top: 10px; left: 650px;" />
                </div>
                <div class="img-baling">
                    <img src="~/images/png hobo lobo/gif hobo segment 6/kincir.gif" alt="" style="position:absolute; width: 1440px; top: 5px; left: 930px;" />
                </div>
                <div class="img-nuklir">
                    <img src="~/images/png hobo lobo/png segment 6/10 nuklier.png" alt="" style="position:absolute; width: 395px; top: 23px; left: 2265px;" />
                </div>
                <div class="img-panelmatahari">
                    <img src="~/images/png hobo lobo/png segment 6/5. panel matahari.png" alt="" style="position:absolute; width: 925px; top: 19px; left: 1805px;" />
                </div>
                <div class="container-fluid" style="position: fixed;">
                    <div class="row">
                        <div id="panelControl" class="col-sm-5 pt-3 pb-1">
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Landing" asp-action="Index">Story 1</a>
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Landing2" asp-action="Index">Story 2</a>
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Landing3" asp-action="Index">Story 3</a>
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Landing4" asp-action="Index">Story 4</a>
                            <a class="btn btn-sm btn-outline-warning active" asp-area="" asp-controller="Landing5" asp-action="Index">Story 5</a>
                            <a class="btn btn-sm btn-outline-warning" asp-area="" asp-controller="Home" asp-action="Index" role="button" aria-disabled="true"><i class="fa fa-home"></i></a>
                            <div class="button-language mt-1">
                                <a class="btn btn-sm btn-outline-warning" href="/id">Indonesia</a>
                                <a class="btn btn-sm btn-outline-warning" href="/en">English</a>
                            </div>
                            <div class="mt-md-2">
                                <p class="glow">Please, Scroll to the Right</p>
                            </div>
                        </div>
                        <div class="col-sm-6 pt-3 narrative">
                            <p class="mb-0">
                                @Localizer["landing_body"]
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="~/js/landing5.js"></script>
    <!-- </body></html> -->
</body>
</html>