Models/News.cs
using System;
using System.Collections.Generic;

namespace PamaWeb.Models
{
    public partial class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public DateTime PublishDate { get; set; }
        public string ImageBaner { get; set; }
        public bool Status { get; set; }
        public bool ExternalLink { get; set; }
        public int VideoImage { get; set; }
        public string ExternalLinkUrl { get; set; }
        public int Type { get; set; }
        public string UrlVideo { get; set; }
        public string SourceUrl { get; set; }
    }
}

Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using PamaWeb.Models;


namespace PamaWeb.Controllers
{
    public class AboutUsController : Controller
    {
        private readonly dbpamaContext _context;

        public AboutUsController(dbpamaContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.AboutUs.First());
        }

        private string _currentLanguage;
        private string CurrentLanguage
        {
            get
            {
                if (!string.IsNullOrEmpty(_currentLanguage))
                    return _currentLanguage;

                if (string.IsNullOrEmpty(_currentLanguage))
                {
                    var feature = HttpContext.Features.Get<IRequestCultureFeature>();
                    _currentLanguage = feature.RequestCulture.Culture.TwoLetterISOLanguageName.ToLower();
                }

                return _currentLanguage;
            }
        }
        public ActionResult RedirectToDefaultCulture()
        {
            var culture = CurrentLanguage;
            if (culture != "en")
                culture = "en";
            return RedirectToAction("Index", new { culture });
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/AwardController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using PamaWeb.Models;

namespace PamaWeb.Controllers
{
    public class AwardController : Controller
    {
        private readonly dbpamaContext _context;

        public AwardController(dbpamaContext context)
        {
            _context = context;
        }
        public IActionResult Index(String param)
        {

            //default page
            try
            {
                if (param.Equals("1"))
                {
                    //all
                    
                    ViewBag.National = new List<Awards>();
                    ViewBag.International = new List<Awards>(); ;
                    ViewBag.General = _context.Awards.OrderByDescending(c => c.Id).ToList();
                }
                else if (param.Equals("2"))
                {
                    //national
                    ViewBag.National = new List<Awards>(); ;
                    ViewBag.International = new List<Awards>(); ;
                    ViewBag.General = _context.Awards.Where(c => c.AwardCategory == 2).OrderByDescending(c => c.Id).ToList();
                }
                else if (param.Equals("3"))
                {
                    //international
                    ViewBag.National = new List<Awards>(); ;
                    ViewBag.International = new List<Awards>(); ;
                    ViewBag.General = _context.Awards.Where(c => c.AwardCategory == 3).OrderByDescending(c => c.Id).ToList();

                }
                else
                {
                    ViewBag.National = _context.Awards.Where(c => c.AwardCategory == 2).Take(2).ToList();
                    ViewBag.International = _context.Awards.Where(c => c.AwardCategory == 3).Take(1).ToList();
                    ViewBag.General = _context.Awards.Where(c => c.AwardCategory != 2 && c.AwardCategory != 3).ToList();
                }
            }
            catch
            {
                //all
                ViewBag.National = new List<Awards>();
                ViewBag.International = new List<Awards>(); ;
                ViewBag.General = _context.Awards.OrderByDescending(c => c.Id).ToList();
            }
            /*
            {
                ViewBag.National = _context.Awards.Where(c => c.AwardCategory == 2).Take(2).ToList();
                ViewBag.International = _context.Awards.Where(c => c.AwardCategory == 3).Take(1).ToList();
                ViewBag.General = _context.Awards.Where(c => c.AwardCategory != 2 && c.AwardCategory != 3).ToList();

            }*/



            return View();
        }

        private string _currentLanguage;
        private string CurrentLanguage
        {
            get
            {
                if (!string.IsNullOrEmpty(_currentLanguage))
                    return _currentLanguage;

                if (string.IsNullOrEmpty(_currentLanguage))
                {
                    var feature = HttpContext.Features.Get<IRequestCultureFeature>();
                    _currentLanguage = feature.RequestCulture.Culture.TwoLetterISOLanguageName.ToLower();
                }

                return _currentLanguage;
            }
        }
        public ActionResult RedirectToDefaultCulture()
        {
            var culture = CurrentLanguage;
            if (culture != "en")
                culture = "en";
            return RedirectToAction("Index", new { culture });
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/BodBocController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PamaWeb.Models;
using Microsoft.AspNetCore.Localization;


namespace PamaWeb.Controllers
{
    public class BodBocController : Controller
    {
        private readonly dbpamaContext _context;

        public BodBocController(dbpamaContext context)
        {
            _context = context;
        }

        private string _currentLanguage;
        private string CurrentLanguage
        {
            get
            {
                if (!string.IsNullOrEmpty(_currentLanguage))
                    return _currentLanguage;

                if (string.IsNullOrEmpty(_currentLanguage))
                {
                    var feature = HttpContext.Features.Get<IRequestCultureFeature>();
                    _currentLanguage = feature.RequestCulture.Culture.TwoLetterISOLanguageName.ToLower();
                }

                return _currentLanguage;
            }
        }

        public IActionResult Index()
        {
            var culture = CurrentLanguage;
            if (culture == "en")
            {
                ViewBag.PresidentKomisaris = _context.BoardOfDirectors.Where(c => c.LevelBodboc == 1 && c.Language == 1).ToList();
                ViewBag.Komisaris = _context.BoardOfDirectors.Where(c => c.LevelBodboc == 2 && c.Language == 1).ToList();
                ViewBag.PresidentDirektur = _context.BoardOfDirectors.Where(c => c.LevelBodboc == 3 && c.Language == 1).ToList();
                ViewBag.Direktur = _context.BoardOfDirectors.Where(c => c.LevelBodboc == 4 && c.Language == 1).ToList();

            }
            else
            {
                ViewBag.PresidentKomisaris = _context.BoardOfDirectors.Where(c => c.LevelBodboc == 1 && c.Language == 2).ToList();
                ViewBag.Komisaris = _context.BoardOfDirectors.Where(c => c.LevelBodboc == 2 && c.Language == 2).ToList();
                ViewBag.PresidentDirektur = _context.BoardOfDirectors.Where(c => c.LevelBodboc == 3 && c.Language == 2).ToList();
                ViewBag.Direktur = _context.BoardOfDirectors.Where(c => c.LevelBodboc == 4 && c.Language == 2).ToList();
            }

            return View();
        }
    }
}

Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using PamaWeb.Models;

namespace PamaWeb.Controllers
{
    public class MapController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
         private string _currentLanguage;
        private string CurrentLanguage
        {
            get
            {
                if (!string.IsNullOrEmpty(_currentLanguage))
                    return _currentLanguage;

                if (string.IsNullOrEmpty(_currentLanguage))
                {
                    var feature = HttpContext.Features.Get<IRequestCultureFeature>();
                    _currentLanguage = feature.RequestCulture.Culture.TwoLetterISOLanguageName.ToLower();
                }

                return _currentLanguage;
            }
        }
        public ActionResult RedirectToDefaultCulture()
        {
            var culture = CurrentLanguage;
            if (culture != "en")
                culture = "en";
            return RedirectToAction("Index", new { culture });
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Localization;
using PamaWeb.Models;

namespace PamaWeb.Controllers
{
    public class NewsController : Controller
    {
        private readonly dbpamaContext _context;

        public NewsController(dbpamaContext context)
        {
            _context = context;
        }
        public IActionResult Index()
         
        {
            ViewBag.News = _context.News.OrderByDescending(c => c.Id).ToList();
            ViewBag.DetailNews = _context.News.ToList();
            ViewBag.Topnews = _context.News.Take(2).ToList();
            ViewBag.Event = _context.News.Where(c=>c.Type==2).ToList();
            ViewBag.Kurs = _context.Kurs.ToList();
            return View();
        }

        public async Task<IActionResult> Details(int? id)
        {

            ViewBag.DetailNews = _context.News.Where(c=>c.Id!=id).Take(3).OrderByDescending(c => c.Id).ToList();

            if (id == null)
            {
                return NotFound();
            }

            var history = await _context.News
                .FirstOrDefaultAsync(m => m.Id == id);
            if (history == null)
            {
                return NotFound();
            }

            return View(history);
        }

        private string _currentLanguage;
        private string CurrentLanguage
        {
            get
            {
                if (!string.IsNullOrEmpty(_currentLanguage))
                    return _currentLanguage;

                if (string.IsNullOrEmpty(_currentLanguage))
                {
                    var feature = HttpContext.Features.Get<IRequestCultureFeature>();
                    _currentLanguage = feature.RequestCulture.Culture.TwoLetterISOLanguageName.ToLower();
                }

                return _currentLanguage;
            }
        }
        public ActionResult RedirectToDefaultCulture()
        {
            var culture = CurrentLanguage;
            if (culture != "en")
                culture = "en";
            return RedirectToAction("Index", new { culture });
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/News/Details.cshtml
@model PamaWeb.Models.News
@{
    List<News> detailnews = ViewBag.DetailNews;

}
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<link rel="stylesheet" href="~/css/detailnews.css" type="text/css" media="screen" runat="server" />

<div class="jumbotron jumbotron-fluid mb-0">
    <div class="container header-title text-white">
        <br />
        <br />
        <br />
        <h1>@Localizer["main_title"]</h1>
        <br />
    </div>
</div>

<div class="container mt-n5 mb-5">
    <div class="row">
        <div class="col-md-8">
            <ul class="breadcrumb m-1">
                <li class="breadcrumb-item text-black-50"><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="breadcrumb-item text-black-50"><a asp-area="" asp-controller="News" asp-action="Index">News</a></li>
                <li class="breadcrumb-item active" aria-current="page">@Html.DisplayFor(model => model.Title)</li>
            </ul>
            <h2 class="news-detail-title py-2">@Html.DisplayFor(model => model.Title)</h2>
            <div class="bg-white px-3 pt-2">
                @{
                    String imageurl = PamaWeb.GeneralClass.GeneralClass.backendUrl + "" + Model.ImageBaner;
                    if (Model.VideoImage == 1)
                    {
                        <iframe src="@Html.DisplayFor(model => model.UrlVideo)" frameborder="0" allowfullscreen class="card-img-top mt-2" style="height: 400px;"></iframe>
                    }
                    else
                    {
                        <img src="@imageurl" alt="" style="width:100%" />
                    }
                }
            </div>
            <div class="publish-date bg-white pl-3 pt-2">Pamapersada.com - @Model.PublishDate.ToString("dd MMMM yyyy")</div>
            <div class="content bg-white p-3"> @Html.Raw(Model.Content)</div>
        </div>
        <div class="col-md-4 mt-2 column-sidenews">
            <h4 class="side-news-title mb-2">Latest News</h4>
            @{
                foreach (var berita in detailnews)
                {
                    <div class="sidenews mb-2 p-2 side-event">
                        @{
                            String sideimageurl = PamaWeb.GeneralClass.GeneralClass.backendUrl + "" + berita.ImageBaner;
                            if (berita.VideoImage == 1)
                            {
                                <div class="embed-responsive embed-responsive-4by3">
                                    <iframe class="embed-responsive-item mt-2" src="@berita.UrlVideo" allowfullscreen></iframe>
                                </div>
                            }
                            else
                            {
                                <img class="mt-2" src=@sideimageurl alt="Card image" style="">

                            }
                        }
                        <p class="sidenews-date font-weight-light text-white m-0"><span class="fa fa-calendar-check"></span>  @berita.PublishDate.ToLongDateString()</p>
                        <a asp-action="Details" asp-route-id="@berita.Id">
                            <p class="sidenews-title font-weight-bold mt-1 text-white">@berita.Title</p>
                        </a>
                    </div>
                }
            }
        </div>
    </div>
</div>

Views/News/Index.cshtml
@{
    List<News> news = ViewBag.News;
}
@{
    Layout = "";
}
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PT PAMAPERSADA NUSANTARA</title>
    <link href="~/faviconpama.ico" rel="shortcut icon" type="image/x-icon" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <!-- Custom Fonts -->
        <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
        <link href="vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/normalize.css" />
    <link rel="stylesheet" href="~/css/news.css" />
    <script src="~/js/clarity.js" type="text/javascript"></script>
    <!-- </head> -->
</head>
<body>
    <header>
        <!-- Navigation -->
        <div>
            <div class="nav" id="nav">
                <a href="javascript:void(0)" id="close" class="close" onclick="closeNav()">&times;</a>
                <a asp-area="" asp-controller="Home" asp-action="Index">@Localizer["menu_home"]</a>
                <a asp-area="" asp-controller="AboutUs" asp-action="Index">@Localizer["menu_aboutus"]</a>
                <a asp-area="" asp-controller="VisiMisi" asp-action="Index">@Localizer["menu_visimisi"]</a>
                <a asp-area="" asp-controller="BodBoc" asp-action="Index">BOC & BOD</a>
                <a asp-area="" asp-controller="BusinessPortfolio" asp-action="Index">@Localizer["menu_bisnis"]</a>
                <a asp-area="" asp-controller="History" asp-action="Index">@Localizer["menu_history"]</a>
                <a asp-area="" asp-controller="Award" asp-action="Index">@Localizer["menu_award"]</a>
                <a asp-area="" asp-controller="Map" asp-action="Index">@Localizer["menu_area"]</a>
                <a asp-area="" asp-controller="News" asp-action="Index">@Localizer["menu_mediaroom"]</a>
                <a asp-area="" asp-controller="Elearning" asp-action="Index">E-Learning</a>
                <a asp-area="" asp-controller="Landing" asp-action="Index">Storyboard</a>
            </div>
            <div>
                <a asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="logo-pama" style="" src="~/images/logopama.png" alt="logopama" />
                </a>
                <span id="open" class="open" onclick="openNav()">
                    &#9776
                </span>
            </div>
        </div>
        <!-- Navigation end -->
    </header>
    <div class="jumbotron jumbotron-fluid mb-0">
        <div class="container header-news text-white align-items-center">
            <br />
            <br />
            <br />
            <div class="mt-2 mb-5">
                @{
                    int indexnews = 0;
                    foreach (var berita in news)
                    {
                        if (indexnews == 0)
                        {
                            <div class="header-top-news">
                                <a asp-action="Details" asp-route-id="@berita.Id">
                                    <h2 class="font-weight-bold">@berita.Title</h2>
                                </a>
                                <p class="m-0">publish : @berita.PublishDate.ToShortDateString()</p>
                                <a href="@berita.SourceUrl" target="_blank">
                                    <p class="font-weight-light m-0 text-truncate">Source : @berita.SourceUrl</p>
                                </a>
                            </div>
                        }
                        indexnews++;
                    }

                }
            </div>
            <hr />
            <div class="row mt-4">
                @{
                    indexnews = 0;
                    foreach (var berita in news)
                    {
                        if (indexnews > 0 && indexnews < 4)
                        {
                            <div class="col-md-4 header-side-news">
                                <a asp-action="Details" asp-route-id="@berita.Id">
                                    <h5 class="font-weight-bold">
                                        @berita.Title
                                    </h5>
                                </a>
                                <p class="m-0">publish : @berita.PublishDate.ToShortDateString()</p>
                                <a href="@berita.SourceUrl" target="_blank">
                                    <p class="font-weight-light m-0 text-truncate">Source : @berita.SourceUrl</p>
                                </a>
                            </div>
                        }
                        indexnews++;
                    }
                }
            </div>
        </div>
    </div>

    <div class="container-fluid rounded my-4 justify-content-around">
        <div class="row">
            <div class="col-8 mt-2">
                <div class="row">
                    @{
                        indexnews = 0;
                        foreach (var berita in news)
                        {
                            if (indexnews > 4)
                            {
                                <div class="col-md-5 ml-md-5">
                                    <div class="card border-0" style="margin: 0 5px 10px 5px;">
                                        @{
                                            String imageurl = PamaWeb.GeneralClass.GeneralClass.backendUrl + "" + berita.ImageBaner;
                                            if (berita.VideoImage == 1)
                                            {
                                                <div class="embed-responsive embed-responsive-16by9">
                                                    <iframe class="embed-responsive-item mt-2" src="@berita.UrlVideo" allowfullscreen></iframe>
                                                </div>
                                            }
                                            else
                                            {
                                                <img class="card-img-top mt-2" src=@imageurl alt="Card image" style="object-fit: cover;" />

                                            }
                                        }
                                        <div class="card-body header-side-news">
                                            @*<span class="badge badge-pill badge-primary">Category</span>*@
                                            <a asp-action="Details" asp-route-id="@berita.Id">
                                                <h5 class="news-card-title card-title m-0">@berita.Title</h5>
                                            </a>
                                            <p class="news-card-date m-0"><span class="fa fa-calendar-check"></span>  @berita.PublishDate.ToLongDateString()</p>
                                            <a href="@berita.SourceUrl" target="_blank">
                                                <p class="font-weight-light m-0 text-truncate news-card-date">Source : @berita.SourceUrl</p>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            }
                            indexnews++;
                        }
                    }
                </div>
            </div>
            <div class="col-4 mt-2 column-event">
                <h4 class="text-white mb-3 events-side-title">@Localizer["events"]</h4>
                @{
                    List<News> even = ViewBag.Event;
                    foreach (var objevent in even)
                    {
                        <div class="event mb-2 p-2 side-event">
                            @{
                                String imageurl = PamaWeb.GeneralClass.GeneralClass.backendUrl + "" + objevent.ImageBaner;
                                if (objevent.VideoImage == 1)
                                {
                                    <div class="embed-responsive embed-responsive-4by3">
                                        <iframe class="embed-responsive-item mt-2" src="@objevent.UrlVideo" allowfullscreen></iframe>
                                    </div>
                                }
                                else
                                {
                                    <img class="mt-2" src=@imageurl alt="News image" style="width:100%">
                                }
                            }
                            <p class="event-date font-weight-light text-white m-0"><span class="fa fa-calendar-check"></span>  @objevent.PublishDate.ToLongDateString()</p>
                            <a asp-action="Details" asp-route-id="@objevent.Id">
                                <p class="event-title font-weight-bold mt-1">@objevent.Title</p>
                            </a>
                        </div>
                    }
                }
                <!-- <hr />
                <div>
                    <h5 class="text-white mb-3 kurs-title">@Localizer["kurs"]</h5>
                    <table class="table table-responsive-sm table-striped table-light table-sm text-center">
                        <thead>
                            <tr>
                                <th>@Localizer["currency"]</th>
                                <th>@Localizer["selling_rate"]</th>
                                <th>@Localizer["buying_rate"]</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                List<Kurs> kurs = ViewBag.Kurs;
                                foreach (var kur in kurs)
                                {
                                    <tr>
                                        <td>@kur.CurrencyCode</td>
                                        <td>@kur.ExchangeRate</td>
                                        <td>@kur.BuyingValue</td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                   -->
            </div>
        </div>
    </div>
    <section class="content-section" id="footers" style="background: rgb(255, 195, 0);">
        <div class="container">
            <div class="p-3">
                <h6 class="font-weight-bold footer-text">Copyright &copy; 2019 - PT Pamapersada Nusantara</h6>
            </div>
        </div>
    </section>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/layout.js" asp-append-version="true"></script>
    <!-- </body></html> -->
</body>
</html>